name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version: [28.1, 29.4]

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install package-lint
        run: |
          emacs --batch -Q \
            --eval "(progn
                      (require 'package)
                      (add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)
                      (package-initialize)
                      (package-refresh-contents)
                      (package-install 'package-lint))"

      - name: Run package-lint
        run: ./script/package-lint

      - name: Run tests
        run: ./script/test
